version: '3.1'

services:
  bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
      target: development
    volumes:
      - ./apps/bot:/usr/src/app
    env_file:
      - ./apps/bot/.env
    networks:
      - internal-network

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb-auth
      - rabbitmq
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal-network

  mongodb-auth:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    networks:
      - internal-network

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - internal-network

  raram-analysis:
    build:
      context: .
      dockerfile: ./apps/raram-analysis/Dockerfile
      target: development
    command: npm run start:dev raram-analysis
    env_file:
      - ./apps/raram-analysis/.env
    depends_on:
      - auth
      - rabbitmq
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
