version: '3.1'

services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb-auth
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal-network

  mongodb-auth:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    networks:
      - internal-network

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - internal-network

  raram-analysis:
    build:
      context: .
      dockerfile: ./apps/raram-analysis/Dockerfile
      target: development
    command: npm run start:dev raram-analysis
    env_file:
      - ./apps/raram-analysis/.env
    depends_on:
      - rabbitmq
      - mongodb-analysis
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal-network

  mongodb-analysis:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27018:27017
    networks:
      - internal-network

  raram-stats:
    build:
      context: .
      dockerfile: ./apps/raram-stats/Dockerfile
      target: development
    command: npm run start:dev raram-stats
    env_file:
      - ./apps/raram-stats/.env
    depends_on:
      - rabbitmq
      - mongodb-stats
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal-network

  mongodb-stats:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27019:27017
    networks:
      - internal-network

  raram-queues:
    build:
      context: .
      dockerfile: ./apps/raram-queues/Dockerfile
      target: development
    command: npm run start:dev raram-queues
    env_file:
      - ./apps/raram-queues/.env
    depends_on:
      - auth
      - rabbitmq
    ports:
      - 3003:3003
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal-network

  gateway:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
    #   - raram-analysis
    #   - raram-stats
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
